Create/Delete setup
mikoMaz/monitoring-via-push-messages pull request #17
Opened 2024-10-29 20:53 UTC by Piaszczysty

Create and Delete setup for alerts with many to many relation

2024-12-09 17:21 UTC, VVojtekMecki approved these changes, later dismissed

2024-12-23 01:57 UTC, mikoMaz commented
And please, pleeeease use auto formatting.
[Java formatting in VS Code](https://code.visualstudio.com/docs/java/java-linting)

2024-12-23 01:58 UTC, mikoMaz requested changes

2024-12-23 01:58 UTC, mikoMaz commented on application.yaml
Why do you duplicate application.yaml? It's already in src/main/resources/

2024-12-23 01:58 UTC, mikoMaz commented on src/main/java/com/example/monitoring/core/alert/AlertController.java
> +    public ResponseEntity<String>addNewAlert(
Please extract content of addNewAlert to some method. It will be painful to test otherwise

2024-12-23 01:58 UTC, mikoMaz commented on src/main/java/com/example/monitoring/core/api/DeviceDataController.java
> +    org.slf4j.Logger  logger =LoggerFactory.getLogger(AuthenticationController.class);
Should be DeviceDataController.
Btw how in a world there is every line marked as new and the same lines are marked as deleted...

2024-12-23 01:58 UTC, mikoMaz commented on src/main/java/com/example/monitoring/core/api/config/SecurityConfiguration.java
> +                        })
Please remove.
Path /api/v1/** is okay for now. It is changing in the upcoming auth0-impl PR so less conflicts to resolve when no filter chain (SecurityConfiguration) is affected.

2024-12-24 10:00 UTC, mikoMaz commented
Please revert 'prettier' commit! In Java, we use 4 spaces for indentation, not 2. Configure prettier. The classes that should be affected are those that you change in this branch, not every class in our project.

2024-12-29 21:38 UTC, mikoMaz approved these changes
I would choose "approve with suggestions" if I were able to.
To change:
- application.yaml
- code formatting

2024-12-29 23:02 UTC, merged